import { randomInt } from "node:crypto";

// Short, common, unambiguous English words used to generate human-typable
// pairing phrases. Not a cryptographic (BIP39) wordlist; no checksum
// guarantees needed since pairing codes are single-use and short-lived.
const WORDLIST = [
  "able", "acid", "aged", "also", "area", "army", "away", "baby", "back", "ball",
  "band", "bank", "base", "bath", "bead", "beam", "bean", "bear", "beat", "bell",
  "belt", "bend", "best", "bike", "bird", "blue", "boat", "body", "bold", "bolt",
  "bone", "book", "boot", "born", "boss", "both", "bowl", "boxy", "boy", "brag",
  "brave", "bread", "break", "brick", "brief", "bring", "broad", "brown", "brush", "build",
  "burn", "bush", "busy", "cage", "cake", "calm", "camp", "card", "care", "case",
  "cash", "cast", "cave", "cell", "chair", "champ", "chart", "chase", "cheap", "check",
  "chief", "child", "chip", "city", "claim", "clamp", "clay", "clean", "clear", "climb",
  "clock", "close", "cloth", "cloud", "club", "coach", "coal", "coast", "coat", "code",
  "coin", "cold", "color", "comb", "come", "cook", "cool", "copy", "cord", "core",
  "corn", "cost", "couch", "could", "count", "court", "cover", "crab", "craft", "crane",
  "crash", "crawl", "cream", "creek", "crest", "crew", "crisp", "crop", "cross", "crowd",
  "crown", "cube", "cure", "curl", "curve", "cushion", "daily", "dairy", "dance", "dark",
  "dash", "data", "dawn", "deal", "dear", "debt", "deck", "deep", "deer", "delta",
  "dense", "depth", "desk", "diary", "dice", "dirt", "dish", "dive", "dock", "doll",
  "door", "dose", "dot", "dove", "draft", "drain", "drama", "draw", "dream", "dress",
  "drift", "drill", "drink", "drive", "drop", "drum", "dry", "duck", "dust", "duty",
  "each", "eagle", "earn", "earth", "ease", "east", "easy", "echo", "edge", "eight",
  "elbow", "elder", "empty", "ends", "enjoy", "enter", "equal", "error", "essay", "even",
  "event", "every", "exact", "exam", "exit", "extra", "eye", "face", "fact", "fade",
  "fair", "fall", "fame", "farm", "fast", "fate", "fear", "feed", "feel", "feet",
  "fence", "field", "fifth", "fifty", "fight", "file", "fill", "film", "find", "fine",
  "fire", "firm", "fish", "fist", "five", "fix", "flag", "flame", "flap", "flash",
  "flat", "fleet", "flesh", "flex", "flick", "flight", "float", "flock", "floor", "flow",
  "fluid", "flute", "foam", "focus", "fold", "folk", "food", "foot", "force", "forge",
  "fork", "form", "fort", "forty", "frame", "free", "fresh", "frog", "front", "frost",
  "fruit", "fuel", "full", "fume", "fund", "funny", "fur", "fury", "fuse", "gain",
  "game", "gap", "garden", "gate", "gear", "gem", "gene", "gift", "girl", "give",
  "glad", "glass", "glide", "glow", "glue", "goal", "goat", "gold", "golf", "good",
  "grab", "grade", "grain", "grand", "grant", "grape", "graph", "grass", "grave", "great",
  "green", "greet", "grid", "grief", "grill", "grind", "grip", "groom", "group", "grove",
  "grow", "guard", "guess", "guest", "guide", "habit", "hair", "half", "hall", "halt",
  "hand", "happy", "hard", "harm", "harp", "hat", "have", "hawk", "haze", "head",
  "heal", "heap", "heart", "heat", "heavy", "hedge", "heel", "hello", "help", "herb",
  "here", "hero", "high", "hill", "hint", "hire", "hold", "hole", "home", "honey",
  "hood", "hook", "hope", "horn", "horse", "host", "hour", "house", "huge", "human",
  "humor", "hunt", "hurry", "hurt", "icon", "idea", "idle", "image", "inch", "index",
  "inner", "input", "iron", "issue", "item", "ivory", "jacket", "jelly", "jewel", "join",
  "joint", "joke", "judge", "juice", "jump", "june", "jury", "just", "keep", "kick",
  "kind", "king", "kite", "knee", "knife", "knock", "know", "label", "lace", "lack",
  "lady", "lake", "lamp", "land", "lane", "large", "last", "late", "laugh", "layer",
  "lead", "leaf", "lean", "learn", "least", "leave", "ledge", "left", "lemon", "level",
  "light", "limit", "line", "link", "lion", "list", "live", "load", "loan", "lobby",
  "local", "lock", "logic", "long", "look", "loop", "loose", "lord", "lost", "loud",
  "lower", "loyal", "lucky", "lunch", "lung", "magic", "maple", "march", "mark", "mask",
  "match", "maybe", "meal", "mean", "meat", "media", "melt", "mend", "menu", "merge",
  "merit", "mesh", "metal", "meter", "midst", "might", "mild", "mile", "milk", "mill",
  "mind", "mine", "minor", "minus", "mint", "minute", "mirror", "miss", "mist", "mixed",
  "model", "moist", "mold", "money", "month", "moon", "moral", "more", "moss", "motor",
  "mount", "mouse", "mouth", "move", "movie", "music", "myth", "nail", "name", "narrow",
  "nasal", "navy", "near", "neat", "neck", "needle", "nerve", "nest", "never", "news",
  "next", "nice", "night", "noble", "noise", "noon", "north", "nose", "note", "noun",
  "novel", "nurse", "nylon", "oasis", "ocean", "offer", "often", "olive", "onion", "open",
  "orange", "order", "organ", "other", "ought", "ounce", "outer", "oven", "owner", "ozone",
  "pace", "pack", "page", "paint", "pair", "palace", "panel", "panic", "paper", "park",
  "part", "party", "paste", "patch", "path", "pause", "peace", "peach", "peak", "pearl",
  "pedal", "penny", "phase", "phone", "photo", "piano", "pick", "piece", "pilot", "pine",
  "pink", "pipe", "pitch", "pixel", "place", "plain", "plan", "plant", "plate", "play",
  "plead", "plot", "plug", "plus", "point", "polar", "pole", "polish", "pond", "pool",
  "porch", "port", "pose", "post", "pound", "power", "press", "price", "pride", "prime",
  "print", "prior", "prize", "proof", "proud", "prove", "pulse", "punch", "pupil", "puppy",
  "purple", "push", "quail", "quart", "queen", "query", "quest", "quick", "quiet", "quilt",
  "quiz", "quote", "race", "radio", "raft", "rail", "rain", "raise", "rally", "ranch",
  "range", "rapid", "rare", "rate", "ratio", "reach", "react", "ready", "realm", "rear",
  "rebel", "recap", "red", "reed", "reef", "relax", "relay", "remix", "reply", "rescue",
  "resin", "rest", "ride", "ridge", "rifle", "right", "rigid", "ring", "rinse", "ripe",
  "rise", "risk", "rival", "river", "roast", "robot", "rock", "rocket", "rod", "role",
  "roll", "roof", "room", "root", "rope", "rose", "rough", "round", "route", "royal",
  "ruby", "rugby", "ruler", "rural", "rush", "rust", "sack", "safe", "sail", "salad",
  "salt", "same", "sand", "satin", "sauce", "save", "scale", "scan", "scarf", "scene",
  "scent", "scoop", "scope", "score", "scout", "screen", "screw", "scrub", "seal", "seat",
  "self", "sense", "shade", "shake", "shape", "share", "shark", "sharp", "sheep", "sheet",
  "shelf", "shell", "shift", "shine", "ship", "shirt", "shock", "shoe", "shoot", "shore",
  "short", "shout", "shown", "shrub", "shut", "siege", "sight", "sign", "silk", "silly",
  "since", "sing", "sister", "site", "sixth", "size", "skate", "sketch", "skill", "skin",
  "skirt", "skull", "skunk", "slab", "slate", "sleek", "sleep", "slice", "slide", "slim",
  "slope", "slot", "slow", "small", "smart", "smell", "smile", "smoke", "snack", "snail",
  "snake", "snap", "sniff", "snow", "soap", "social", "sock", "soda", "solar", "solid",
  "solve", "song", "sonic", "sort", "soul", "sound", "soup", "south", "space", "spare",
  "spark", "speak", "spear", "speed", "spell", "spend", "spice", "spike", "spin", "spine",
  "spire", "split", "spoon", "sport", "spot", "spray", "spread", "spring", "spy", "squad",
  "square", "stack", "staff", "stage", "stair", "stamp", "stand", "star", "start", "state",
  "stay", "steak", "steam", "steel", "steep", "stem", "step", "stick", "stiff", "still",
  "sting", "stir", "stock", "stone", "stool", "stop", "store", "storm", "story", "stove",
  "straw", "stream", "street", "stress", "strike", "string", "strip", "study", "stuff", "style",
  "sugar", "suit", "summer", "sunny", "super", "surf", "swarm", "sweep", "sweet", "swift",
  "swim", "swing", "sword", "table", "tag", "tail", "take", "tale", "talk", "tall",
  "tank", "tap", "tape", "target", "task", "taste", "team", "teeth", "tell", "tempo",
  "tend", "tennis", "tent", "term", "test", "text", "thank", "theme", "thick", "thin",
  "thing", "think", "third", "thread", "throat", "throw", "thumb", "tide", "tidy", "tiger",
  "tight", "tile", "timer", "tiny", "tip", "tire", "title", "toast", "today", "token",
  "tone", "tongue", "tool", "tooth", "topic", "torch", "total", "touch", "tough", "tour",
  "tower", "town", "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash",
  "treat", "tree", "trend", "trial", "tribe", "trick", "trim", "trip", "troop", "truck",
  "true", "trust", "truth", "tube", "tulip", "tuna", "tune", "tunnel", "turbo", "turn",
  "tusk", "twice", "twig", "twin", "twist", "type", "ultra", "uncle", "under", "union",
  "unit", "unity", "until", "upper", "upset", "urban", "usage", "used", "user", "usual",
  "vague", "valid", "valley", "value", "valve", "vapor", "vast", "vault", "venue", "verb",
  "verse", "video", "view", "villa", "vinyl", "violet", "visit", "visual", "vital", "vivid",
  "vocal", "voice", "void", "volume", "vote", "wagon", "waist", "wait", "wake", "walk",
  "wall", "want", "warm", "wash", "waste", "watch", "water", "wave", "weak", "wealth",
  "wear", "weave", "wedge", "week", "weigh", "weird", "welt", "west", "whale", "wheat",
  "wheel", "while", "white", "whole", "wide", "width", "wild", "will", "wind", "wine",
  "wing", "wink", "winter", "wire", "wise", "wish", "witty", "wolf", "wood", "wool",
  "word", "work", "world", "worry", "worth", "wrap", "wrist", "write", "yard", "yarn",
  "year", "yield", "young", "youth", "zebra", "zero", "zone",
] as const;

export function generatePairingPhrase(wordCount = 12): string {
  const used = new Set<number>();
  const words: string[] = [];

  while (words.length < wordCount) {
    const index = randomInt(WORDLIST.length);
    if (used.has(index)) continue;
    used.add(index);
    words.push(WORDLIST[index]);
  }

  return words.join(" ");
}
